# Generated by Django 6.0.7 on 2026-07-26 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji-Icon', max_length=8)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('points', models.PositiveIntegerField(default=0)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chores', to=settings.AUTH_USER_MODEL)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_chores', to='accounts.familymember')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='accounts.household')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Täglich'), ('WEEKLY', 'Wöchentlich'), ('MONTHLY', 'Monatlich')], max_length=10)),
                ('interval', models.PositiveSmallIntegerField(default=1, help_text='Alle N Einheiten, z. B. 2 = jede zweite Woche.')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='Wochentage bei WEEKLY (0=Mo … 6=So), z. B. [0, 3].')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Tag im Monat bei MONTHLY (1–31).', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('chore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='chores.chore')),
            ],
        ),
        migrations.CreateModel(
            name='ChoreInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('DONE', 'Erledigt'), ('SKIPPED', 'Übersprungen')], default='OPEN', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_instances', to='accounts.familymember')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chores.chore')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_instances', to='accounts.familymember')),
            ],
            options={
                'ordering': ['due_date', 'chore__title'],
                'constraints': [models.UniqueConstraint(fields=('chore', 'due_date'), name='unique_chore_instance_per_day')],
            },
        ),
    ]
