# Generated by Django 5.2 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0004_multiple_assignees"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="image",
            field=models.FileField(blank=True, help_text="Optionales Bild zur Aufgabe.", upload_to="chore-images/"),
        ),
    ]
