# Generated by Django 6.0.7 on 2026-09-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_familymember_notification_service"),
        ("chores", "0005_chore_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="is_always_available",
            field=models.BooleanField(
                default=False,
                help_text="Bleibt nach jeder Erledigung aktiv und kann mehrfach am Tag zählen.",
            ),
        ),
        migrations.CreateModel(
            name="ChoreCompletion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("chore", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="always_available_completions", to="chores.chore")),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="always_available_completions", to="accounts.familymember")),
            ],
            options={"ordering": ["-completed_at"]},
        ),
    ]
