# Generated by Django 6.0.7 on 2026-09-19 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_familymember_notification_service'),
        ('chores', '0005_chore_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OPEN_TASKS', 'Offene Aufgaben'), ('CHORE', 'Bestimmte Aufgabe'), ('MESSAGE', 'Eigener Hinweis')], default='OPEN_TASKS', max_length=16)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('time', models.TimeField()),
                ('weekdays', models.JSONField(default=list, help_text='0=Montag bis 6=Sonntag')),
                ('enabled', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chores.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.familymember')),
            ],
            options={
                'ordering': ['time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(null=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='reminders.reminder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reminder', 'date'), name='unique_reminder_delivery_per_day')],
            },
        ),
    ]
