# Generated by Django 5.2 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="completion_jingle",
            field=models.CharField(choices=[("SPARKLE", "Glitzer"), ("BELL", "Glocke"), ("FANFARE", "Fanfare"), ("BUBBLE", "Blubber"), ("SOFT", "Sanft")], default="SPARKLE", max_length=16),
        ),
        migrations.AddField(
            model_name="familymember",
            name="undo_jingle",
            field=models.CharField(choices=[("SPARKLE", "Glitzer"), ("BELL", "Glocke"), ("FANFARE", "Fanfare"), ("BUBBLE", "Blubber"), ("SOFT", "Sanft")], default="SOFT", max_length=16),
        ),
    ]
