# Generated by Django 6.0.7 on 2026-09-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_familymember_jingles'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='notification_service',
            field=models.CharField(blank=True, help_text='Home-Assistant-Dienst für das Handy, z. B. mobile_app_mein_handy.', max_length=160),
        ),
    ]
