/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Einfacher Health-Check für Monitoring und Frontend-Anbindung.
         */
        get: operations["gc_family_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Meldet ein Elternkonto mit E-Mail und Passwort an.
         */
        post: operations["accounts_api_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Erstellt aus einem gültigen Eltern-Refresh-Token einen neuen Access-Token.
         */
        post: operations["accounts_api_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Liefert den aktuellen Token-Kontext einschließlich Haushalt und Profil.
         */
        get: operations["accounts_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/household/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Device Members
         * @description Liefert Profile des aktuell am Familiengerät bekannten Haushalts.
         */
        get: operations["accounts_api_device_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pin Login
         * @description Schaltet für ein Kind mit PIN einen kurzlebigen, profilgebundenen Token aus.
         */
        post: operations["accounts_api_pin_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/child-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Child Login
         * @description Meldet ein Kind direkt am sichtbaren Familien-Dashboard per PIN an.
         */
        post: operations["accounts_api_child_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Family Pin Login
         * @description Einfacher sechsstelliger Login für Kinder und Eltern ohne Profilauswahl.
         */
        post: operations["accounts_api_family_pin_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/household/manage-members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Managed Members
         * @description Listet Mitglieder inklusive Eltern-E-Mail für die Elternverwaltung.
         */
        get: operations["accounts_api_managed_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/household/manage-members/parents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Parent Member
         * @description Legt einen weiteren Eltern-Login samt Profil im aktuellen Haushalt an.
         */
        post: operations["accounts_api_create_parent_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/household/manage-members/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Child Member
         * @description Legt ein Kinderprofil mit einer sechsstelligen PIN an.
         */
        post: operations["accounts_api_create_child_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/household/manage-members/children/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Child Member
         * @description Aktualisiert ein Kinderprofil und bei Bedarf dessen PIN.
         */
        put: operations["accounts_api_update_child_member"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/household/manage-members/parents/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Parent Member */
        put: operations["accounts_api_update_parent_member"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["chores_api_list_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Instances
         * @description Aufgaben-Instanzen im Zeitfenster (Default: heute).
         */
        get: operations["chores_api_list_instances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats
         * @description Liefert Punkte und Tages-Streak für das aktuell angemeldete Profil.
         */
        get: operations["chores_api_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/instances/{instance_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Instance */
        post: operations["chores_api_complete_instance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/instances/{instance_id}/uncomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Uncomplete Instance
         * @description Nimmt den eigenen vollständigen oder halben Aufgabenanteil zurück.
         */
        post: operations["chores_api_uncomplete_instance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/instances/{instance_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip Instance */
        post: operations["chores_api_skip_instance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/instances/{instance_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reopen Instance
         * @description Nimmt eine Erledigung zurück. Das dürfen ausschließlich Eltern.
         */
        post: operations["chores_api_reopen_instance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chores
         * @description Listet Aufgaben-Definitionen für die Elternverwaltung.
         */
        get: operations["chores_api_list_chores"];
        put?: never;
        /**
         * Create Chore
         * @description Erstellt eine Aufgabe mit fester Zuweisung und materialisiert ihre Instanzen.
         */
        post: operations["chores_api_create_chore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/{chore_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Chore
         * @description Aktualisiert eine Aufgabe und erzeugt ihre künftigen Instanzen neu.
         */
        put: operations["chores_api_update_chore"];
        post?: never;
        /**
         * Delete Chore
         * @description Löscht eine Aufgaben-Definition samt zugehöriger Instanzen.
         */
        delete: operations["chores_api_delete_chore"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/{chore_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Chore Image
         * @description Hinterlegt ein optionales Bild an einer Aufgabe.
         */
        post: operations["chores_api_upload_chore_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public Dashboard
         * @description Öffentliche Familienansicht für die laufende Sonntag-bis-Samstag-Woche.
         */
        get: operations["chores_api_public_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /** TokenPairOut */
        TokenPairOut: {
            /** Access */
            access: string;
            /** Refresh */
            refresh: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** AccessTokenOut */
        AccessTokenOut: {
            /** Access */
            access: string;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh */
            refresh: string;
        };
        /**
         * AuthMemberOut
         * @description Eindeutiger Schema-Name, damit sich die OpenAPI-Schemata nicht mit
         *     der öffentlichen Aufgaben-Mitgliederliste überschneiden.
         */
        AuthMemberOut: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Color */
            color: string;
            /** Emoji */
            emoji: string;
            /** Completion Jingle */
            completion_jingle: string;
            /** Undo Jingle */
            undo_jingle: string;
        };
        /** HouseholdOut */
        HouseholdOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** MeOut */
        MeOut: {
            /** Authenticated */
            authenticated: boolean;
            user?: components["schemas"]["UserOut"] | null;
            household: components["schemas"]["HouseholdOut"];
            member: components["schemas"]["AuthMemberOut"];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Can Access Backend */
            can_access_backend: boolean;
        };
        /** MemberOut */
        MemberOut: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Color */
            color: string;
            /** Emoji */
            emoji: string;
        };
        /** PinIn */
        PinIn: {
            /** Member Id */
            member_id: number;
            /** Pin */
            pin: string;
        };
        /** FamilyPinIn */
        FamilyPinIn: {
            /** Pin */
            pin: string;
        };
        /** ManagedMemberOut */
        ManagedMemberOut: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Color */
            color: string;
            /** Emoji */
            emoji: string;
            /** Completion Jingle */
            completion_jingle: string;
            /** Undo Jingle */
            undo_jingle: string;
            /** Email */
            email: string | null;
        };
        /** ParentMemberIn */
        ParentMemberIn: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Pin */
            pin: string;
            /**
             * Color
             * @default #2563eb
             */
            color: string;
            /**
             * Emoji
             * @default
             */
            emoji: string;
        };
        /** ChildMemberIn */
        ChildMemberIn: {
            /** Display Name */
            display_name: string;
            /** Pin */
            pin: string;
            /**
             * Color
             * @default #6366f1
             */
            color: string;
            /**
             * Emoji
             * @default
             */
            emoji: string;
            /**
             * Completion Jingle
             * @default SPARKLE
             */
            completion_jingle: string;
            /**
             * Undo Jingle
             * @default SOFT
             */
            undo_jingle: string;
        };
        /** ChildMemberUpdateIn */
        ChildMemberUpdateIn: {
            /** Display Name */
            display_name: string;
            /** Pin */
            pin?: string | null;
            /**
             * Color
             * @default #6366f1
             */
            color: string;
            /**
             * Emoji
             * @default
             */
            emoji: string;
            /** Completion Jingle */
            completion_jingle?: string | null;
            /** Undo Jingle */
            undo_jingle?: string | null;
        };
        /** ParentMemberUpdateIn */
        ParentMemberUpdateIn: {
            /** Display Name */
            display_name: string;
            /** Pin */
            pin?: string | null;
            /**
             * Color
             * @default #2563eb
             */
            color: string;
            /**
             * Emoji
             * @default
             */
            emoji: string;
        };
        /** ContributionOut */
        ContributionOut: {
            /** Member Id */
            member_id: number;
            /** Member Name */
            member_name: string;
            /** Member Emoji */
            member_emoji: string;
            /** Share */
            share: number;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
        };
        /** InstanceOut */
        InstanceOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Color */
            color: string;
            /** Image Url */
            image_url: string | null;
            /** Points */
            points: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Active Until */
            active_until: string | null;
            /** Category */
            category: string;
            /** Status */
            status: string;
            /** Assigned Member Id */
            assigned_member_id: number | null;
            /** Assigned Member Name */
            assigned_member_name: string | null;
            /** Assigned Member Ids */
            assigned_member_ids: number[];
            /** Assigned Member Names */
            assigned_member_names: string[];
            /** Completed At */
            completed_at: string | null;
            /** Completed By Id */
            completed_by_id: number | null;
            /** Completed By Name */
            completed_by_name: string | null;
            /** Contributions */
            contributions: components["schemas"]["ContributionOut"][];
        };
        /** StatsOut */
        StatsOut: {
            /** Points Today */
            points_today: number;
            /** Current Streak */
            current_streak: number;
        };
        /** CompleteIn */
        CompleteIn: {
            /** Member Id */
            member_id?: number | null;
            /**
             * Share
             * @default false
             */
            share: boolean;
        };
        /** ChoreOut */
        ChoreOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Color */
            color: string;
            /** Image Url */
            image_url: string | null;
            /** Points */
            points: number;
            /** Is Recurring */
            is_recurring: boolean;
            /** Default Assignee Id */
            default_assignee_id: number | null;
            /** Default Assignee Ids */
            default_assignee_ids: number[];
            /** Due Date */
            due_date: string | null;
            /** End Date */
            end_date: string | null;
            recurrence: components["schemas"]["RecurrenceOut"] | null;
        };
        /** RecurrenceOut */
        RecurrenceOut: {
            /** Frequency */
            frequency: string;
            /**
             * Interval
             * @default 1
             */
            interval: number;
            /**
             * Weekdays
             * @default []
             */
            weekdays: number[];
            /** Day Of Month */
            day_of_month?: number | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
        };
        /** ChoreIn */
        ChoreIn: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Icon
             * @default
             */
            icon: string;
            /**
             * Color
             * @default #6366f1
             */
            color: string;
            /**
             * Points
             * @default 0
             */
            points: number;
            /**
             * Is Recurring
             * @default false
             */
            is_recurring: boolean;
            /** Default Assignee Id */
            default_assignee_id?: number | null;
            /**
             * Default Assignee Ids
             * @default []
             */
            default_assignee_ids: number[];
            /** Due Date */
            due_date?: string | null;
            /** End Date */
            end_date?: string | null;
            recurrence?: components["schemas"]["RecurrenceIn"] | null;
        };
        /** RecurrenceIn */
        RecurrenceIn: {
            /** Frequency */
            frequency: string;
            /**
             * Interval
             * @default 1
             */
            interval: number;
            /**
             * Weekdays
             * @default []
             */
            weekdays: number[];
            /** Day Of Month */
            day_of_month?: number | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
        };
        /** MemberWeeklyStatsOut */
        MemberWeeklyStatsOut: {
            /** Member Id */
            member_id: number;
            /** Display Name */
            display_name: string;
            /** Emoji */
            emoji: string;
            /** Color */
            color: string;
            /** Completed Tasks */
            completed_tasks: number;
            /** Points */
            points: number;
        };
        /** PublicDashboardOut */
        PublicDashboardOut: {
            /** Members */
            members: components["schemas"]["MemberOut"][];
            /** Instances */
            instances: components["schemas"]["InstanceOut"][];
            /** Stats */
            stats: components["schemas"]["MemberWeeklyStatsOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    gc_family_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    accounts_api_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
        };
    };
    accounts_api_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenOut"];
                };
            };
        };
    };
    accounts_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    accounts_api_device_members: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
        };
    };
    accounts_api_pin_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenOut"];
                };
            };
        };
    };
    accounts_api_child_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenOut"];
                };
            };
        };
    };
    accounts_api_family_pin_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyPinIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenOut"];
                };
            };
        };
    };
    accounts_api_managed_members: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedMemberOut"][];
                };
            };
        };
    };
    accounts_api_create_parent_member: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParentMemberIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedMemberOut"];
                };
            };
        };
    };
    accounts_api_create_child_member: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChildMemberIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedMemberOut"];
                };
            };
        };
    };
    accounts_api_update_child_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChildMemberUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedMemberOut"];
                };
            };
        };
    };
    accounts_api_update_parent_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParentMemberUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedMemberOut"];
                };
            };
        };
    };
    chores_api_list_members: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
        };
    };
    chores_api_list_instances: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                member_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceOut"][];
                };
            };
        };
    };
    chores_api_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    chores_api_complete_instance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceOut"];
                };
            };
        };
    };
    chores_api_uncomplete_instance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceOut"];
                };
            };
        };
    };
    chores_api_skip_instance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceOut"];
                };
            };
        };
    };
    chores_api_reopen_instance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceOut"];
                };
            };
        };
    };
    chores_api_list_chores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoreOut"][];
                };
            };
        };
    };
    chores_api_create_chore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChoreIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoreOut"];
                };
            };
        };
    };
    chores_api_update_chore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chore_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChoreIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoreOut"];
                };
            };
        };
    };
    chores_api_delete_chore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chore_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chores_api_upload_chore_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chore_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Image
                     * Format: binary
                     */
                    image: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoreOut"];
                };
            };
        };
    };
    chores_api_public_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicDashboardOut"];
                };
            };
        };
    };
}
