/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Einfacher Health-Check für Monitoring und Frontend-Anbindung.
         */
        get: operations["gc_family_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Meldet ein Elternkonto mit E-Mail und Passwort an.
         */
        post: operations["accounts_api_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Erstellt aus einem gültigen Eltern-Refresh-Token einen neuen Access-Token.
         */
        post: operations["accounts_api_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Liefert den aktuellen Token-Kontext einschließlich Haushalt und Profil.
         */
        get: operations["accounts_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/household/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Device Members
         * @description Liefert Profile des aktuell am Familiengerät bekannten Haushalts.
         */
        get: operations["accounts_api_device_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pin Login
         * @description Schaltet für ein Kind mit PIN einen kurzlebigen, profilgebundenen Token aus.
         */
        post: operations["accounts_api_pin_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["chores_api_list_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Instances
         * @description Aufgaben-Instanzen im Zeitfenster (Default: heute).
         */
        get: operations["chores_api_list_instances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats
         * @description Liefert Punkte und Tages-Streak für das aktuell angemeldete Profil.
         */
        get: operations["chores_api_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/instances/{instance_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Instance */
        post: operations["chores_api_complete_instance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/instances/{instance_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip Instance */
        post: operations["chores_api_skip_instance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chores
         * @description Listet Aufgaben-Definitionen für die Elternverwaltung.
         */
        get: operations["chores_api_list_chores"];
        put?: never;
        /**
         * Create Chore
         * @description Erstellt eine Aufgabe mit fester Zuweisung und materialisiert ihre Instanzen.
         */
        post: operations["chores_api_create_chore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/{chore_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Chore
         * @description Aktualisiert eine Aufgabe und erzeugt ihre künftigen Instanzen neu.
         */
        put: operations["chores_api_update_chore"];
        post?: never;
        /**
         * Delete Chore
         * @description Löscht eine Aufgaben-Definition samt zugehöriger Instanzen.
         */
        delete: operations["chores_api_delete_chore"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /** TokenPairOut */
        TokenPairOut: {
            /** Access */
            access: string;
            /** Refresh */
            refresh: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** AccessTokenOut */
        AccessTokenOut: {
            /** Access */
            access: string;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh */
            refresh: string;
        };
        /** HouseholdOut */
        HouseholdOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** MeOut */
        MeOut: {
            /** Authenticated */
            authenticated: boolean;
            user?: components["schemas"]["UserOut"] | null;
            household: components["schemas"]["HouseholdOut"];
            member: components["schemas"]["MemberOut"];
        };
        /** MemberOut */
        MemberOut: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Color */
            color: string;
            /** Emoji */
            emoji: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
        };
        /** PinIn */
        PinIn: {
            /** Member Id */
            member_id: number;
            /** Pin */
            pin: string;
        };
        /** InstanceOut */
        InstanceOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Icon */
            icon: string;
            /** Color */
            color: string;
            /** Points */
            points: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Status */
            status: string;
            /** Assigned Member Id */
            assigned_member_id: number | null;
            /** Assigned Member Name */
            assigned_member_name: string | null;
        };
        /** StatsOut */
        StatsOut: {
            /** Points Today */
            points_today: number;
            /** Current Streak */
            current_streak: number;
        };
        /** CompleteIn */
        CompleteIn: {
            /** Member Id */
            member_id?: number | null;
        };
        /** ChoreOut */
        ChoreOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Color */
            color: string;
            /** Points */
            points: number;
            /** Is Recurring */
            is_recurring: boolean;
            /** Default Assignee Id */
            default_assignee_id: number | null;
            /** Due Date */
            due_date: string | null;
            recurrence: components["schemas"]["RecurrenceOut"] | null;
        };
        /** RecurrenceOut */
        RecurrenceOut: {
            /** Frequency */
            frequency: string;
            /**
             * Interval
             * @default 1
             */
            interval: number;
            /**
             * Weekdays
             * @default []
             */
            weekdays: number[];
            /** Day Of Month */
            day_of_month?: number | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
        };
        /** ChoreIn */
        ChoreIn: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Icon
             * @default
             */
            icon: string;
            /**
             * Color
             * @default #6366f1
             */
            color: string;
            /**
             * Points
             * @default 0
             */
            points: number;
            /**
             * Is Recurring
             * @default false
             */
            is_recurring: boolean;
            /** Default Assignee Id */
            default_assignee_id?: number | null;
            /** Due Date */
            due_date?: string | null;
            recurrence?: components["schemas"]["RecurrenceIn"] | null;
        };
        /** RecurrenceIn */
        RecurrenceIn: {
            /** Frequency */
            frequency: string;
            /**
             * Interval
             * @default 1
             */
            interval: number;
            /**
             * Weekdays
             * @default []
             */
            weekdays: number[];
            /** Day Of Month */
            day_of_month?: number | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    gc_family_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    accounts_api_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
        };
    };
    accounts_api_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenOut"];
                };
            };
        };
    };
    accounts_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    accounts_api_device_members: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
        };
    };
    accounts_api_pin_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenOut"];
                };
            };
        };
    };
    chores_api_list_members: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
        };
    };
    chores_api_list_instances: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                member_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceOut"][];
                };
            };
        };
    };
    chores_api_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    chores_api_complete_instance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceOut"];
                };
            };
        };
    };
    chores_api_skip_instance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceOut"];
                };
            };
        };
    };
    chores_api_list_chores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoreOut"][];
                };
            };
        };
    };
    chores_api_create_chore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChoreIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoreOut"];
                };
            };
        };
    };
    chores_api_update_chore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chore_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChoreIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoreOut"];
                };
            };
        };
    };
    chores_api_delete_chore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chore_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
